[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/bouk/monkey"
  version = "v1.0.1"

[[constraint]]
  name = "github.com/fatih/structs"
  version = "v1.1.0"

[[constraint]]
  name = "github.com/dghubble/sling"
  branch = "v1.2.0"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "v1.9.2"

[[constraint]]
  name = "github.com/shopspring/decimal"
  version = "1.1.0"

[[constraint]]
  name = "github.com/rs/zerolog"
  version = "v1.11.0"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "v3.3.8"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "v1.3.0"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "v1.3.0"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "v6.10.2"
